title: Aidan Hurst
logo: /assets/img/2025.JPG
description: Aspiring Cybersecurity Analyst, Independent Learner 

**Email: aidan.l.hurst@gmail.com**
[**LinkedIn**](https://www.linkedin.com/in/aidan-hurst-445453303 )
#show_downloads: true
theme: jekyll-theme-minimal
